version: "3"

services:
  bot-api:
    build:
      context: .
      dockerfile: docker/adonis.dockerfile
    container_name: adonis_bot_dev
    command: npm run dev
    ports:
      - "3101:3333"
    expose:
      - "3333"
    volumes:
      - ./backend:/var/app
      - ./.env:/var/app/.env
      - /var/app/node_modules
    environment:
      - TZ=Asia/Bangkok

  bot-redis:
    image: redis:6.2
    container_name: redis_bot_dev
    ports:
      - "6311:6379"
